name: Docker Image Build
on:
  push:
    branches: ["**","!master"]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        tags: mumblevoip/mumo
